/// <reference types="node" />

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

declare module "raxios" {
  export type RaxiosResponseType =
    | 'arraybuffer'
    | 'buffer'
    | 'blob'
    | 'bytes'
    | string

  export type RaxiosHeaders = Record<string, string>

  export interface RaxiosNativeResponse {
    status: number
    data: string | Buffer
    headers: RaxiosHeaders
  }

  export interface RaxiosRequestConfig<D = any> {
    url?: string
    method?: string
    baseURL?: string
    headers?: RaxiosHeaders
    params?: Record<string, any>
    data?: D
    timeout?: number
    responseType?: RaxiosResponseType
    transformRequest?: RaxiosTransformRequest | RaxiosTransformRequest[]
    transformResponse?: RaxiosTransformResponse | RaxiosTransformResponse[]
  }

  export interface RaxiosResponse<T = any> {
    data: T
    status: number
    headers: RaxiosHeaders
    config: RaxiosRequestConfig
  }

  export type RaxiosTransformRequest = (data: any, headers: RaxiosHeaders) => any

  export type RaxiosTransformResponse = (data: any) => any

  export interface RaxiosError extends Error {
    config?: RaxiosRequestConfig
    code?: string
    response?: RaxiosResponse
    status?: number
    isRaxiosError: boolean
  }

  export interface InterceptorManager<V> {
    use(
      onFulfilled?: (value: V) => V | Promise<V>,
      onRejected?: (error: any) => any
    ): number
    eject(id: number): void
    forEach(fn: (handler: { fulfilled?: Function; rejected?: Function }) => void): void
  }

  export interface RaxiosInstance {
    <T = any>(url: string, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    <T = any>(config: RaxiosRequestConfig): Promise<RaxiosResponse<T>>

    defaults: RaxiosRequestConfig
    interceptors: {
      request: InterceptorManager<RaxiosRequestConfig>
      response: InterceptorManager<RaxiosResponse>
    }

    get<T = any>(url: string, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    delete<T = any>(url: string, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    head<T = any>(url: string, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    options<T = any>(url: string, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    post<T = any>(url: string, data?: any, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    put<T = any>(url: string, data?: any, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
    patch<T = any>(url: string, data?: any, config?: RaxiosRequestConfig): Promise<RaxiosResponse<T>>
  }

  export interface RaxiosStatic extends RaxiosInstance {
    create(config?: RaxiosRequestConfig): RaxiosInstance
    isRaxiosError(error: any): error is RaxiosError
    all<T>(promises: Array<Promise<T>>): Promise<T[]>
    spread<T extends any[], R>(callback: (...args: T) => R): (arr: T) => R
  }

  export function request(
    method: string,
    url: string,
    headers?: RaxiosHeaders | undefined | null,
    body?: string | undefined | null,
    timeout?: number | undefined | null,
    responseType?: string | undefined | null
  ): Promise<RaxiosNativeResponse>

  const raxios: RaxiosStatic
  export default raxios
}
